/*

  NB-IoT / LTE-M Mobile Country Codes for Arduino.

  This file is partially autogenerated from
  *  https://en.wikipedia.org/wiki/Mobile_country_code
  *  https://www.gsma.com/iot/mobile-iot-commercial-launches

  If your operator is missing, please, contact <>

  Created 2018-07-26 12:38:16.322649'
  by RetrievePLMNs.py

  Reviewed 2018-07-27
  by Giampaolo Mancini

*/

struct MobileOperator {
  const char* MNC;
  const char* Brand;
};

struct MobileCountry {
  const char* ISO;
  const char* MCC;
  const int OperatorsNum;
  const MobileOperator *Operators;
  const char* Nation;
};

MobileOperator Operators_AU[] = {
  {"01", "Telstra"},
  {"03", "Vodafone"},
  {"71", "Telstra"},
  {"72", "Telstra"}
};

MobileOperator Operators_AT[] = {
  {"03", "T-Mobile AT"},
  {"04", "T-Mobile AT"}
};

MobileOperator Operators_BE[] = {
  {"10", "Orange"}
};

MobileOperator Operators_BY[] = {
  {"01", "Velcom"}
};

MobileOperator Operators_CN[] = {
  {"00", "China Mobile"},
  {"01", "China Unicom"},
  {"03", "China Telecom"},
  {"09", "China Unicom"}
};

MobileOperator Operators_HR[] = {
  {"01", "T-Mobile"}
};

MobileOperator Operators_CZ[] = {
  {"03", "Vodafone"},
  {"99", "Vodafone"}
};

MobileOperator Operators_DK[] = {
  {"01", "TDC"},
  {"10", "TDC"},
  {"20", "Telia"}
};

MobileOperator Operators_FI[] = {
  {"03", "DNA"},
  {"05", "Elisa"},
  {"12", "DNA"},
  {"21", "Elisa-"},
  {"36", "Sonera"},
  {"91", "Sonera"}
};

MobileOperator Operators_DE[] = {
  {"01", "Telekom"},
  {"02", "Vodafone"},
  {"09", "Vodafone"},
  {"78", "Telekom"}
};

MobileOperator Operators_GR[] = {
  {"01", "Cosmote"},
  {"02", "Cosmote"}
};

MobileOperator Operators_HK[] = {
  {"03", "3"},
  {"12", "CMCC HK"}
};

MobileOperator Operators_IE[] = {
  {"01", "Vodafone"}
};

MobileOperator Operators_IT[] = {
  {"01", "TIM"},
  {"10", "Vodafone"}
};

MobileOperator Operators_JP[] = {
  {"50", "au"},
  {"51", "au"},
  {"52", "au"},
  {"53", "au"},
  {"54", "au"},
  {"70", "au"},
  {"71", "au"},
  {"72", "au"},
  {"73", "au"},
  {"74", "au"},
  {"75", "au"},
  {"76", "au"},
  {"77", "au"},
  {"78", "au"}
};

MobileOperator Operators_MX[] = {
  {"010", "AT&T"},
  {"050", "AT&T"},
  {"090", "AT&T"}
};

MobileOperator Operators_NL[] = {
  {"04", "Vodafone"},
  {"08", "KPN"},
  {"10", "KPN"},
  {"20", "T-Mobile"}
};

MobileOperator Operators_NO[] = {
  {"02", "Telia"}
};

MobileOperator Operators_PL[] = {
  {"02", "T-Mobile"},
  {"10", "T-Mobile"},
  {"34", "NetWorkS!"}
};

MobileOperator Operators_SG[] = {
  {"01", "SingTel"},
  {"03", "M1"},
  {"07", "SingTel"}
};

MobileOperator Operators_SK[] = {
  {"02", "Telekom"},
  {"04", "Telekom"}
};

MobileOperator Operators_KR[] = {
  {"02", "KT"},
  {"04", "KT"},
  {"07", "KT"}
};

MobileOperator Operators_ZA[] = {
  {"01", "Vodacom"}
};

MobileOperator Operators_ES[] = {
  {"01", "Vodafone"},
  {"05", "Movistar"},
  {"06", "Vodafone"},
  {"07", "Movistar"}
};

MobileOperator Operators_LK[] = {
  {"01", "Mobitel"},
  {"02", "Dialog"},
};

MobileOperator Operators_SE[] = {
  {"01", "Telia"}
};

MobileOperator Operators_TW[] = {
  {"01", "FarEasTone"},
  {"05", "APTG"},
  {"06", "FarEasTone"},
  {"11", "Chunghwa"},
  {"88", "FarEasTone"},
  {"92", "Chunghwa"}
};

MobileOperator Operators_TH[] = {
  {"00", "True"},
  {"03", "AIS"}
};

MobileOperator Operators_TR[] = {
  {"01", "Turkcell"},
  {"02", "Vodafone"}
};

MobileOperator Operators_AE[] = {
  {"02", "Etisalat"}
};

MobileOperator Operators_US_310[] = {
  {"004", "Verizon"},
  {"005", "Verizon"},
  {"006", "Verizon"},
  {"012", "Verizon"},
  {"170", "AT&T"},
  {"410", "AT&T"}
};

MobileOperator Operators_US_311[] = {
  {"012", "Verizon"},
  {"480", "Verizon"}
};

#define _LEN(X) sizeof(X) / sizeof(MobileOperator)

MobileCountry MCCs[] = {
  {"AU", "505", _LEN(Operators_AU), Operators_AU, "Australia"},
  {"AT", "232", _LEN(Operators_AT), Operators_AT, "Austria"},
  {"BY", "257", _LEN(Operators_BY), Operators_BY, "Belarus"},
  {"BE", "206", _LEN(Operators_BE), Operators_BE, "Belgium"},
  {"CN", "460", _LEN(Operators_CN), Operators_CN, "China"},
  {"HR", "219", _LEN(Operators_HR), Operators_HR, "Croatia"},
  {"CZ", "230", _LEN(Operators_CZ), Operators_CZ, "Czech Republic"},
  {"DK", "238", _LEN(Operators_DK), Operators_DK, "Denmark"},
  {"FI", "244", _LEN(Operators_FI), Operators_FI, "Finland"},
  {"DE", "262", _LEN(Operators_DE), Operators_DE, "Germany"},
  {"GR", "202", _LEN(Operators_GR), Operators_GR, "Greece"},
  {"HK", "454", _LEN(Operators_HK), Operators_HK, "Hong Kong"},
  {"IE", "272", _LEN(Operators_IE), Operators_IE, "Ireland"},
  {"IT", "222", _LEN(Operators_IT), Operators_IT, "Italy"},
  {"JP", "440", _LEN(Operators_JP), Operators_JP, "Japan"},
  {"MX", "334", _LEN(Operators_MX), Operators_MX, "Mexico"},
  {"NL", "204", _LEN(Operators_NL), Operators_NL, "Netherlands"},
  {"NO", "242", _LEN(Operators_NO), Operators_NO, "Norway"},
  {"PL", "260", _LEN(Operators_PL), Operators_PL, "Poland"},
  {"SG", "525", _LEN(Operators_SG), Operators_SG, "Singapore"},
  {"SK", "231", _LEN(Operators_SK), Operators_SK, "Slovakia"},
  {"ZA", "655", _LEN(Operators_ZA), Operators_ZA, "South Africa"},
  {"KR", "450", _LEN(Operators_KR), Operators_KR, "South Korea"},
  {"ES", "214", _LEN(Operators_ES), Operators_ES, "Spain"},
  {"LK", "413", _LEN(Operators_LK), Operators_LK, "Sri Lanka"},
  {"SE", "240", _LEN(Operators_SE), Operators_SE, "Sweden"},
  {"TW", "466", _LEN(Operators_TW), Operators_TW, "Taiwan"},
  {"TH", "520", _LEN(Operators_TH), Operators_TH, "Thailand"},
  {"TR", "286", _LEN(Operators_TR), Operators_TR, "Turkey"},
  {"AE", "424", _LEN(Operators_AE), Operators_AE, "United Arab Emirates"},
  {"US", "310", _LEN(Operators_US_310), Operators_US_310, "United States of America (310)"},
  {"US", "311", _LEN(Operators_US_311), Operators_US_311, "United States of America (311)"}
};

const int MCCs_NUM = sizeof(MCCs) / sizeof(MobileCountry);
